type Salutation {
  greeting: String!
  tone: String!
}

type Message {
    message: String!
    tone: String!
}

type Transmission {
  salutation: Salutation!
  message: Message!
  recipient: Recipient!
  received: Boolean
}

type Recipient {
  firstName: String!
  lastName: String!
  tone: String!
  transmissions: [Transmission] @relation
}

type Query {
  allRecipients: [Recipient!]
  allSalutations: [Salutation!]
  allMessages: [Message!]
}